var text = 
`[
 {
   "id": 1,
   "Gender": "Female",
   "Year": 1,
   "Uni": "CMU",
   "MB": "INFJ",
   "Enneagram": "One",
   "SG1": "Serving",
   "SG2": "Shepherding",
   "SG3": "Showing Mercy"
 },
 {
   "id": 2,
   "Gender": "Female",
   "Year": 1,
   "Uni": "CMU",
   "MB": "ISFJ",
   "Enneagram": "One",
   "SG1": "Serving",
   "SG2": "Showing Mercy",
   "SG3": "Teaching"
 },
 {
   "id": 3,
   "Gender": "Male",
   "Year": 5,
   "Uni": "CMU",
   "MB": "ISFJ",
   "Enneagram": "One",
   "SG1": "Shepherding",
   "SG2": "Showing Mercy",
   "SG3": "Serving"
 },
  {
   "id": 4,
   "Gender": "Male",
   "Year": 4,
   "Uni": "CMU",
   "MB": "ESFP",
   "Enneagram": "One",
   "SG1": "Serving",
   "SG2": "Shepherding",
   "SG3": "Showing Mercy"
 },
 {
   "id": 5,
   "Gender": "Male",
   "Year": 1,
   "Uni": "Pitt",
   "MB": "ENFP",
   "Enneagram": "Two",
   "SG1": "Serving",
   "SG2": "Showing Mercy",
   "SG3": "Shepherding"
 },
 {
   "id": 6,
   "Gender": "Female",
   "Year": 4,
   "Uni": "Pitt",
   "MB": "ESFJ",
   "Enneagram": "Two",
   "SG1": "Showing Mercy",
   "SG2": "Serving",
   "SG3": "Exhortation"
 },
 {
   "id": 7,
   "Gender": "Female",
   "Year": 2,
   "Uni": "CMU",
   "MB": "INFJ",
   "Enneagram": "Two",
   "SG1": "Showing Mercy",
   "SG2": "Exhortation",
   "SG3": "Serving"
 },
 {
   "id": 8,
   "Gender": "Male",
   "Year": 1,
   "Uni": "CMU",
   "MB": "INFJ",
   "Enneagram": "Two",
   "SG1": "Shepherding",
   "SG2": "Teaching",
   "SG3": "Giving"
 },
 {
   "id": 9,
   "Gender": "Male",
   "Year": 2,
   "Uni": "CMU",
   "MB": "INFJ",
   "Enneagram": "Two",
   "SG1": "Showing Mercy",
   "SG2": "Shepherding",
   "SG3": "Serving"
 },
 {
   "id": 10,
   "Gender": "Male",
   "Year": 1,
   "Uni": "CMU",
   "MB": "INFP",
   "Enneagram": "Two",
   "SG1": "Shepherding",
   "SG2": "Serving",
   "SG3": "Administration"
 },
 {
   "id": 11,
   "Gender": "Female",
   "Year": 2,
   "Uni": "CMU",
   "MB": "ISFJ",
   "Enneagram": "Two",
   "SG1": "Showing Mercy",
   "SG2": "Shepherding",
   "SG3": "Exhortation"
 },
 {
   "id": 12,
   "Gender": "Female",
   "Year": 1,
   "Uni": "CMU",
   "MB": "ENTJ",
   "Enneagram": "Three",
   "SG1": "Giving",
   "SG2": "Administration",
   "SG3": "Showing Mercy"
 },
 {
   "id": 13,
   "Gender": "Male",
   "Year": 3,
   "Uni": "CMU",
   "MB": "ENTJ",
   "Enneagram": "Three",
   "SG1": "Teaching",
   "SG2": "Administration",
   "SG3": "Shepherding"
 },
 {
   "id": 14,
   "Gender": "Female",
   "Year": 4,
   "Uni": "CMU",
   "MB": "INFJ",
   "Enneagram": "Three",
   "SG1": "Teaching",
   "SG2": "Exhortation",
   "SG3": "Shepherding"
 },
 {
   "id": 15,
   "Gender": "Female",
   "Year": 3,
   "Uni": "CMU",
   "MB": "ISFJ",
   "Enneagram": "Three",
   "SG1": "Showing Mercy",
   "SG2": "Serving",
   "SG3": "Administration"
 },
 {
   "id": 16,
   "Gender": "Female",
   "Year": 4,
   "Uni": "Pitt",
   "MB": "ISFP",
   "Enneagram": "Three",
   "SG1": "Administration",
   "SG2": "Exhortation",
   "SG3": "Shepherding"
 },
 {
   "id": 17,
   "Gender": "Female",
   "Year": 5,
   "Uni": "CMU",
   "MB": "ENFP",
   "Enneagram": "Four",
   "SG1": "Shepherding",
   "SG2": "Evangelism",
   "SG3": "Showing Mercy"
 },
 {
   "id": 18,
   "Gender": "Female",
   "Year": 5,
   "Uni": "CMU",
   "MB": "INFJ",
   "Enneagram": "Four",
   "SG1": "Showing Mercy",
   "SG2": "Evangelism",
   "SG3": "Teaching"
 },
 {
   "id": 19,
   "Gender": "Female",
   "Year": 1,
   "Uni": "CMU",
   "MB": "INFP",
   "Enneagram": "Four",
   "SG1": "Showing Mercy",
   "SG2": "Shepherding",
   "SG3": "Serving"
 },
 {
   "id": 20,
   "Gender": "Male",
   "Year": 4,
   "Uni": "CMU",
   "MB": "INFP",
   "Enneagram": "Four",
   "SG1": "Showing Mercy",
   "SG2": "Shepherding",
   "SG3": "Serving"
 },
 {
   "id": 21,
   "Gender": "Female",
   "Year": 2,
   "Uni": "CMU",
   "MB": "INTP",
   "Enneagram": "Five",
   "SG1": "Giving",
   "SG2": "Serving",
   "SG3": "Teaching"
 },
 {
   "id": 22,
   "Gender": "Male",
   "Year": 2,
   "Uni": "Other",
   "MB": "INTP",
   "Enneagram": "Five",
   "SG1": "Giving",
   "SG2": "Teaching",
   "SG3": "Exhortation"
 },
 {
   "id": 23,
   "Gender": "Male",
   "Year": 4,
   "Uni": "CMU",
   "MB": "ISTJ",
   "Enneagram": "Five",
   "SG1": "Administration",
   "SG2": "Teaching",
   "SG3": "Giving"
 },
 {
   "id": 24,
   "Gender": "Female",
   "Year": 1,
   "Uni": "CMU",
   "MB": "ESFJ",
   "Enneagram": "Six",
   "SG1": "Exhortation",
   "SG2": "Showing Mercy",
   "SG3": "Teaching"
 },
 {
   "id": 25,
   "Gender": "Female",
   "Year": 1,
   "Uni": "CMU",
   "MB": "INTP",
   "Enneagram": "Six",
   "SG1": "Serving",
   "SG2": "Giving",
   "SG3": "Exhortation"
 },
 {
   "id": 26,
   "Gender": "Female",
   "Year": 1,
   "Uni": "CMU",
   "MB": "ISFP",
   "Enneagram": "Six",
   "SG1": "Showing Mercy",
   "SG2": "Serving",
   "SG3": "Giving"
 },
 {
   "id": 27,
   "Gender": "Female",
   "Year": 4,
   "Uni": "Pitt",
   "MB": "ISFP",
   "Enneagram": "Six",
   "SG1": "Showing Mercy",
   "SG2": "Shepherding",
   "SG3": "Serving"
 },
 {
   "id": 28,
   "Gender": "Female",
   "Year": 3,
   "Uni": "CMU",
   "MB": "ISTJ",
   "Enneagram": "Six",
   "SG1": "Exhortation",
   "SG2": "Teaching",
   "SG3": "Serving"
 },
 {
   "id": 29,
   "Gender": "Female",
   "Year": 2,
   "Uni": "CMU",
   "MB": "ESFP",
   "Enneagram": "Seven",
   "SG1": "Showing Mercy",
   "SG2": "Administration",
   "SG3": "Serving"
 },
 {
   "id": 30,
   "Gender": "Male",
   "Year": 3,
   "Uni": "CMU",
   "MB": "ESFP",
   "Enneagram": "Seven",
   "SG1": "Evangelism",
   "SG2": "Shepherding",
   "SG3": "Showing Mercy"
 },
 {
   "id": 31,
   "Gender": "Female",
   "Year": 4,
   "Uni": "CMU",
   "MB": "ENFP",
   "Enneagram": "Eight",
   "SG1": "Shepherding",
   "SG2": "Showing Mercy",
   "SG3": "Evangelism"
 },
 {
   "id": 32,
   "Gender": "Male",
   "Year": 1,
   "Uni": "CMU",
   "MB": "INTP",
   "Enneagram": "Eight",
   "SG1": "Shepherding",
   "SG2": "Prophecy",
   "SG3": "Exhortation"
 },
 {
   "id": 33,
   "Gender": "Male",
   "Year": 3,
   "Uni": "Pitt",
   "MB": "ENFJ",
   "Enneagram": "Nine",
   "SG1": "Administration",
   "SG2": "Serving",
   "SG3": "Evangelism"
 },
 {
   "id": 34,
   "Gender": "Female",
   "Year": 5,
   "Uni": "CMU",
   "MB": "ESFJ",
   "Enneagram": "Nine",
   "SG1": "Showing Mercy",
   "SG2": "Shepherding",
   "SG3": "Administration"
 },
 {
   "id": 35,
   "Gender": "Male",
   "Year": 5,
   "Uni": "Pitt",
   "MB": "INFJ",
   "Enneagram": "Nine",
   "SG1": "Exhortation",
   "SG2": "Showing Mercy",
   "SG3": "Serving"
 },
 {
   "id": 36,
   "Gender": "Male",
   "Year": 2,
   "Uni": "CMU",
   "MB": "INFP",
   "Enneagram": "Nine",
   "SG1": "Shepherding",
   "SG2": "Prophecy",
   "SG3": "Showing Mercy"
 },
 {
   "id": 37,
   "Gender": "Female",
   "Year": 1,
   "Uni": "Pitt",
   "MB": "ISFJ",
   "Enneagram": "Nine",
   "SG1": "Showing Mercy",
   "SG2": "Exhortation",
   "SG3": "Teaching"
 },
 {
   "id": 38,
   "Gender": "Male",
   "Year": 4,
   "Uni": "CMU",
   "MB": "ISFJ",
   "Enneagram": "Nine",
   "SG1": "Showing Mercy",
   "SG2": "Serving",
   "SG3": "Shepherding"
 },
 {
   "id": 39,
   "Gender": "Male",
   "Year": 1,
   "Uni": "CMU",
   "MB": "ISFP",
   "Enneagram": "Nine",
   "SG1": "Shepherding",
   "SG2": "Showing Mercy",
   "SG3": "Prophecy"
 },
 {
   "id": 40,
   "Gender": "Female",
   "Year": 4,
   "Uni": "Pitt",
   "MB": "ISTJ",
   "Enneagram": "Nine",
   "SG1": "Giving",
   "SG2": "Shepherding",
   "SG3": "Showing Mercy"
 },
 {
   "id": 41,
   "Gender": "Male",
   "Year": 4,
   "Uni": "Pitt",
   "MB": "ISTJ",
   "Enneagram": "Nine",
   "SG1": "Giving",
   "SG2": "Serving",
   "SG3": "Administration"
 },
 {
   "id": 42,
   "Gender": "Female",
   "Year": 1,
   "Uni": "CMU",
   "MB": "ENFP",
   "Enneagram": "Three",
   "SG1": "Showing Mercy",
   "SG2": "Evangelism",
   "SG3": "Prophecy"
 }
]
`